I need to emulate a do-while loop in a Python program. Unfortunately, the following straightforward code does not work:Instead of "1,2,3,done", it prints the following output:What can I do in order to catch the \'stop iteration\' exception and break a while\nloop properly?An example of why such a thing may be needed is shown below as pseudocode.State machine:I am not sure what you are trying to do. You can implement a do-while loop like this:Or:What are you doing trying to use a do while loop to print the stuff in the list? Why not just use:Update:So do you have a list of lines? And you want to keep iterating through it? How about: Does that seem like something close to what you would want? With your code example, it would be:Here\'s a very simple way to emulate a do-while loop:The key features of a do-while loop are that the loop body always executes at least once, and that the condition is evaluated at the bottom of the loop body.  The control structure show here accomplishes both of these with no need for exceptions or break statements.  It does introduce one extra Boolean variable.My code below might be a useful implementation, highlighting the main difference between do-while vs while as I understand it. So in this one case, you always go through the loop at least once.Exception will break the loop, so you might as well handle it outside the loop.I guess that the problem with your code is that behaviour of break inside except is not defined. Generally break goes only one level up, so e.g. break inside try goes directly to finally (if it exists) an out of the try, but not out of the loop.Related PEP: http://www.python.org/dev/peps/pep-3136 \nRelated question: Breaking out of nested loops->You can do a function:But\n1) It\'s ugly.\n2) Condition should be a function with one parameter, supposed to be filled by stuff (it\'s the only reason not to use the classic while loop.)Here is a crazier solution of a different pattern -- using coroutines. The code is still very similar, but with one important difference; there are no exit conditions at all! The coroutine (chain of coroutines really) just stops when you stop feeding it with data.The code above collects all tokens as tuples in tokens and I assume there is no difference between .append() and .add() in the original code.for a do - while loop containing try statementsalternatively, when there\'s no need for the \'finally\' clauseQuick hack:Use like so:Why don\'t you just do?See if this helps :Set a flag inside the exception handler and check it before working on the s.