This question already has an answer here:Is there a way to get functionality similar to mkdir -p on the shell from within Python.  I am looking for a solution other than a system call.  I am sure the code is less than 20 lines, and I am wondering if someone has already written it?mkdir -p functionality as follows:For Python \xe2\x89\xa5 3.2, os.makedirs has an optional third argument exist_ok that, when true, enables the mkdir -p functionality \xe2\x80\x94unless mode is provided and the existing directory has different permissions than the intended ones; in that case, OSError is raised as previously.In Python >=3.2, that\'sIn earlier versions, use @tzot\'s answer.This is easier than trapping the exception:Disclaimer This approach requires two system calls which is more susceptible to race conditions under certain environments/conditions.  If you\'re writing something more sophisticated than a simple throwaway script running in a controlled environment, you\'re better off going with the accepted answer that requires only one system call.UPDATE 2012-07-27I\'m tempted to delete this answer, but I think there\'s value in the comment thread below.  As such, I\'m converting it to a wiki.  Recently, I found this distutils.dir_util.mkpath:mkdir -p gives you an error if you the file already exists:So a refinement to the previous suggestions would be to re-raise the exception if os.path.isdir returns False (when checking for errno.EEXIST).(Update) See also this highly similar question; I agree with the accepted answer (and caveats) except I would recommend os.path.isdir instead of os.path.exists.(Update) Per a suggestion in the comments, the full function would look like:As mentioned in the other solutions, we want to be able to hit the file system once while mimicking the behaviour of mkdir -p.  I don\'t think that this is possible to do, but we should get as close as possible.Code first, explanation later:As the comments to @tzot\'s answer indicate there are problems with checking whether you can create a directory before you actually create it: you can\'t tell whether someone has changed the file system in the meantime.  That also fits in with Python\'s style of asking for forgiveness, not permission.So the first thing we should do is try to make the directory, then if it goes wrong, work out why.As Jacob Gabrielson points out, one of the cases we must look for is the case where a file already exists where we are trying to put the directory.  With mkdir -p:The analogous behaviour in Python would be to raise an exception.So we have to work out if this was the case.  Unfortunately, we can\'t.  We get the same error message back from makedirs whether a directory exists (good) or a file exists preventing the creation of the directory (bad).The only way to work out what happened is to inspect the file system again to see if there is a directory there.  If there is, then return silently, otherwise raise the exception.The only problem is that the file system may be in a different state now than when makedirs was called.  eg: a file existed causing makedirs to fail, but now a directory is in its place.  That doesn\'t really matter that much, because the the function will only exit silently without raising an exception when at the time of the last file system call the directory existed.I think Asa\'s answer is essentially correct, but you could extend it a little to act more like mkdir -p, either:orThese both handle the case where the path already exists silently but let other errors bubble up.With Pathlib from python3 standard library:If parents is true, any missing parents of this path are created as\n  needed; they are created with the default permissions without taking\n  mode into account (mimicking the POSIX mkdir -p command).\n  If exist_ok is false (the default), an FileExistsError is raised if\n  the target directory already exists.If exist_ok is true, FileExistsError exceptions will be ignored (same\n  behavior as the POSIX mkdir -p command), but only if the last path\n  component is not an existing non-directory file.Changed in version 3.5: The exist_ok parameter was added.Function declaration;usage :I\'ve had success with the following personally, but my function should probably be called something like \'ensure this directory exists\':based on @Dave C\'s answer but with a bug fixed where part of the tree already exists