Why am I getting this error?\nI\'m confused.What do you need to know to answer my question?socket is a module, containing the class socket.You need to do socket.socket(...) or from socket import socket:Notice that the error here is pretty easy to understand: if module object is not callable, you are probably calling a module object! What\'s a module object? It\'s the type of thing you get when you import a module.But even if you don\'t understand that (which is fine, it\'s often confusing that classes, modules, functions etc are all just objects like everything else), there\'s a pretty easy way to start debugging:Add to __init__.py, e.g.:Then, you will have an instance of your class ready when you import it into another script:Here is another gotcha, that took me awhile to see even after reading these posts. I was setting up a script to call my python bin scripts. I was getting the module not callable too.My zig was that I was doing the following:when my zag needed to do the following:In summary, double check your package and module nesting. What I am trying to do is have a scripts directory that does not have the *.py extension, and still have the \'bin\' modules to be in mypackage/bin and these have my *.py extension. I am new to packaging, and trying to follow the standards as I am interpreting them. So, I have at the setup root: If this is not compliant with standard, please let me know.Assume that the content of YourClass.py is:If you use:In this way, I got TypeError: \'module\' object is not callable.But, if you use:It works for me.It seems like what you\'ve done is imported the socket module as import socket. Therefore socket is the module. You either need to change that line to self.serv = socket.socket(socket.AF_INET, socket.SOCK_STREAM), as well as every other use of the socket module, or change the import statement to from socket import socket.Or you\'ve got an import socket after your from socket import *:I know this thread is a year old, but the real problem is in your working directory.I believe that the working directory is C:\\Users\\Administrator\\Documents\\Mibot\\oops\\. Please check for the file named socket.py in this directory. Once you find it, rename or move it. When you import socket, socket.py from the current directory is used instead of the socket.py from Python\'s directory. Hope this helped. :)Note: Never use the file names from Python\'s directory to save your program\'s file name; it will conflict with your program(s).A simple way to solve this problem is export thePYTHONPATH variable enviroment. For example, for Python 2.6 in Debian/GNU Linux: In other operating systems, you would first find the location of this module or the socket.py file.When configuring an console_scripts entrypoint in setup.py I found this issue existed when the endpoint was a module or package rather than a function within the module.For exampleShould have beenSo that it would refer to a callable function rather than the module itself. It seems to make no difference if the module has a if __name__ == \'__main__\': block. This will not make the module callable. 